import { EmailLog, EmailEvent } from '@/shared/types/emailTracking';

export const mockEmailLogs: EmailLog[] = [
  {
    id: '1',
    templateId: '1',
    recipientIds: ['1', '2', '3'],
    recipientEmails: ['john.doe@example.com', 'jane.smith@example.com', 'mike.johnson@example.com'],
    subject: 'Interview Invitation - Software Engineer Position',
    body: 'Dear candidate, we are pleased to invite you...',
    status: 'sent',
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    opens: 2,
    clicks: 1,
    bounces: [],
    createdBy: 'admin',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    recipientIds: ['4', '5'],
    recipientEmails: ['alice.wong@example.com', 'bob.brown@example.com'],
    subject: 'Application Status Update',
    body: 'Thank you for your application. We wanted to update you...',
    status: 'sent',
    sentAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    opens: 1,
    clicks: 0,
    bounces: [],
    createdBy: 'admin',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    templateId: '2',
    recipientIds: ['6'],
    recipientEmails: ['charlie.davis@example.com'],
    subject: 'Rejection Notice',
    body: 'We appreciate your interest in our company...',
    status: 'sent',
    sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    opens: 1,
    clicks: 0,
    bounces: [],
    createdBy: 'admin',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    recipientIds: ['7', '8', '9'],
    recipientEmails: ['diana.lee@example.com', 'evan.miller@example.com', 'fiona.clark@example.com'],
    subject: 'Welcome to Our Interview Process',
    body: 'Congratulations on advancing to the next stage...',
    status: 'scheduled',
    scheduledFor: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    opens: 0,
    clicks: 0,
    bounces: [],
    createdBy: 'admin',
    createdAt: new Date().toISOString(),
  },
];

export const mockEmailEvents: EmailEvent[] = [
  {
    id: '1',
    emailLogId: '1',
    recipientEmail: 'john.doe@example.com',
    eventType: 'sent',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    emailLogId: '1',
    recipientEmail: 'john.doe@example.com',
    eventType: 'delivered',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    emailLogId: '1',
    recipientEmail: 'john.doe@example.com',
    eventType: 'opened',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    emailLogId: '1',
    recipientEmail: 'john.doe@example.com',
    eventType: 'clicked',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    emailLogId: '1',
    recipientEmail: 'jane.smith@example.com',
    eventType: 'sent',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    emailLogId: '1',
    recipientEmail: 'jane.smith@example.com',
    eventType: 'delivered',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    emailLogId: '1',
    recipientEmail: 'jane.smith@example.com',
    eventType: 'opened',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
  },
];
